import argparse
import gzip
import json
import sys
from pathlib import Path

from wildcard_data import add_world_arguments, world_query, write_lines

MAX_LEVEL = 63
MIN_AMOUNT = 25

parser = argparse.ArgumentParser(description="Writes ascension_wildcard_boss_marks from the 'Dropped by' list of the "
                                             "archived db.ascension.gg page of item 375250 (Rune of Ascension).")
parser.add_argument("--page", type=Path, required=True, help="saved HTML of the archived item page")
add_world_arguments(parser)
parser.add_argument("output")
args = parser.parse_args()

raw = args.page.read_bytes()
page = (gzip.decompress(raw) if raw[:2] == b"\x1f\x8b" else raw).decode("utf-8", "replace")
data = page.index("[", page.index('"data":', page.index('"id":"dropped-by"')))
droppers, _ = json.JSONDecoder().raw_decode(page, data)
droppers = [row for row in droppers if row.get("maxlevel", 0) <= MAX_LEVEL and row["stack"][0] >= MIN_AMOUNT]
query = world_query(args)
existing = {int(row[0]) for row in query("SELECT `entry` FROM `creature_template` WHERE `entry` IN (" +
                                         ",".join(str(row["id"]) for row in droppers) + ")")}
marks = sorted((row["id"], row["stack"][0], row["name"]) for row in droppers if row["id"] in existing)

lines = [
    "-- On Darkmoon - Season 10 Wildcard every dungeon and raid boss dropped Runes of Ascension "
    "(375250, party loot, so",
    "-- each group member got the full amount): 25 or 50 in normal dungeons, 75 and 175 for Heroic bosses, 400-725 in",
    "-- raids and 2500-7000 for the final raid bosses. Amounts are the 'Dropped by' list of item 375250 on",
    "-- db.ascension.gg archived 2026-08-04 during the season, limited to level 63 creatures that exist here. The",
    "-- server grants them on the kill because a loot stack holds at most 255.",
    "-- Generated by apps/coa-wildcard/boss_marks.py.",
    "DROP TABLE IF EXISTS `ascension_wildcard_boss_marks`;",
    "CREATE TABLE `ascension_wildcard_boss_marks` (",
    "  `CreatureEntry` INT UNSIGNED NOT NULL,",
    "  `Amount` INT UNSIGNED NOT NULL,",
    "  PRIMARY KEY (`CreatureEntry`)",
    ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
    "",
    "DELETE FROM `ascension_wildcard_boss_marks`;",
    "INSERT INTO `ascension_wildcard_boss_marks` (`CreatureEntry`, `Amount`) VALUES",
]
for index, (entry, amount, name) in enumerate(marks):
    end = "," if index + 1 < len(marks) else ";"
    lines.append(f"({entry}, {amount}){end} -- {name}")
write_lines(args.output, lines)
print(len(marks), "bosses", file=sys.stderr)
