#ifndef COA_LEGENDARY_CATALOG_H
#define COA_LEGENDARY_CATALOG_H

#include "CoALegendaryRules.h"
#include <array>

namespace CoALegendary
{
    inline constexpr std::array<Design, DesignCount> Catalog =
    {{
        { "Bloodoath Signet", 12, Power::Offense,
            Condition::AfterKill, Profile::Strength, 11, 0, 0, 0 },
        { "Wayfarers of the Northern Wastes", 12, Power::Movement,
            Condition::OutOfCombat, Profile::Strength, 8, 0, 15, 0 },
        { "Cask of the Last Ancestor", 12, Power::Signature,
            Condition::Always, Profile::Strength, 12, 805808, 12, 42 },
        { "Soulfire Loop", 13, Power::Offense,
            Condition::Healthy, Profile::Caster, 11, 0, 0, 0 },
        { "Gravewalker Sandals", 13, Power::Movement,
            Condition::AfterKill, Profile::Caster, 8, 0, 18, 0 },
        { "Mask of the Laughing Loa", 13, Power::Signature,
            Condition::Always, Profile::Caster, 12, 802087, 12, 5 },
        { "Oathbreaker Seal", 14, Power::Offense,
            Condition::Wounded, Profile::AgilityHybrid, 11, 0, 0, 0 },
        { "Cindertrail Treads", 14, Power::Movement,
            Condition::Wounded, Profile::AgilityHybrid, 8, 0, 20, 0 },
        { "Shard of the Fallen World", 14, Power::Signature,
            Condition::Always, Profile::AgilityHybrid, 12, 801895, 12, 2 },
        { "Ashen Verdict", 15, Power::Offense,
            Condition::AfterKill, Profile::Agility, 11, 0, 0, 0 },
        { "Boots of the Accused", 15, Power::Movement,
            Condition::Healthy, Profile::Agility, 8, 0, 10, 0 },
        { "Last Stake of the Inquisitor", 15, Power::Signature,
            Condition::Always, Profile::Agility, 12, 680537, 12, 3 },
        { "Thunderbound Band", 16, Power::Offense,
            Condition::Healthy, Profile::StrengthHybrid, 11, 0, 0, 0 },
        { "Stormroamer Striders", 16, Power::Movement,
            Condition::OutOfCombat, Profile::StrengthHybrid, 8, 0, 15, 0 },
        { "Splinter of the Skyfather", 16, Power::Signature,
            Condition::Always, Profile::StrengthHybrid, 12, 801847, 12, 1 },
        { "Xorothian Bloodseal", 17, Power::Offense,
            Condition::Wounded, Profile::Strength, 11, 0, 0, 0 },
        { "Sabatons of the Unbroken Rider", 17, Power::Movement,
            Condition::AfterKill, Profile::Strength, 8, 0, 18, 0 },
        { "Chain of the Seventh Gate", 17, Power::Signature,
            Condition::Always, Profile::Strength, 12, 800081, 12, 1 },
        { "Bastion of the Resolute", 18, Power::Offense,
            Condition::AfterKill, Profile::Strength, 11, 0, 0, 0 },
        { "March of the Unyielding", 18, Power::Movement,
            Condition::Wounded, Profile::Strength, 8, 0, 20, 0 },
        { "Heart of the Stone Colossus", 18, Power::Signature,
            Condition::Always, Profile::Strength, 12, 803129, 12, 1 },
        { "Vow of the Dawnblade", 19, Power::Offense,
            Condition::Healthy, Profile::AgilityHybrid, 11, 0, 0, 0 },
        { "Silver Pilgrim Treads", 19, Power::Movement,
            Condition::Healthy, Profile::AgilityHybrid, 8, 0, 10, 0 },
        { "Scales of the Final Reckoning", 19, Power::Signature,
            Condition::Always, Profile::AgilityHybrid, 12, 805421, 12, 14 },
        { "Crimson Covenant", 20, Power::Offense,
            Condition::Wounded, Profile::Caster, 11, 0, 0, 0 },
        { "Footfalls of the Restless Heart", 20, Power::Movement,
            Condition::OutOfCombat, Profile::Caster, 8, 0, 15, 0 },
        { "Vial of the First Sanguine", 20, Power::Signature,
            Condition::Always, Profile::Caster, 12, 504260, 12, 8 },
        { "Signet of the Silent Hunt", 21, Power::Offense,
            Condition::AfterKill, Profile::Agility, 11, 0, 0, 0 },
        { "Path of the White Stag", 21, Power::Movement,
            Condition::AfterKill, Profile::Agility, 8, 0, 18, 0 },
        { "Eye of the Far Horizon", 21, Power::Signature,
            Condition::Always, Profile::Agility, 12, 500075, 12, 26 },
        { "Loop of the Missing Hour", 22, Power::Offense,
            Condition::Healthy, Profile::Caster, 11, 0, 0, 0 },
        { "Footsteps Between Seconds", 22, Power::Movement,
            Condition::Wounded, Profile::Caster, 8, 0, 20, 0 },
        { "Prism of Unwritten Tomorrows", 22, Power::Signature,
            Condition::Always, Profile::Caster, 12, 801292, 12, 11 },
        { "Gravebound Promise", 23, Power::Offense,
            Condition::Wounded, Profile::Caster, 11, 0, 0, 0 },
        { "Pale Road Slippers", 23, Power::Movement,
            Condition::Healthy, Profile::Caster, 8, 0, 10, 0 },
        { "Phylactery of Borrowed Breath", 23, Power::Offense,
            Condition::InCombat, Profile::Caster, 12, 0, 0, 0 },
        { "Coal of the Undying Flame", 24, Power::Offense,
            Condition::AfterKill, Profile::Caster, 11, 0, 0, 0 },
        { "Emberwake Boots", 24, Power::Movement,
            Condition::OutOfCombat, Profile::Caster, 8, 0, 15, 0 },
        { "Crown of the Falling Sun", 24, Power::Signature,
            Condition::Always, Profile::Caster, 12, 801905, 12, 19 },
        { "Pact of the Hollow Saint", 25, Power::Offense,
            Condition::Healthy, Profile::StrengthHybrid, 11, 0, 0, 0 },
        { "Steps of the Unseen Choir", 25, Power::Movement,
            Condition::AfterKill, Profile::StrengthHybrid, 8, 0, 18, 0 },
        { "Scripture of the Nameless One", 25, Power::Signature,
            Condition::Always, Profile::StrengthHybrid, 12, 500714, 12, 4 },
        { "Orbit of the Lost Constellation", 26, Power::Offense,
            Condition::Wounded, Profile::Caster, 11, 0, 0, 0 },
        { "Astral Wanderer Treads", 26, Power::Movement,
            Condition::Wounded, Profile::Caster, 8, 0, 20, 0 },
        { "Fragment of the First Star", 26, Power::Signature,
            Condition::Always, Profile::Caster, 12, 800497, 12, 40 },
        { "Halo of the Returning Dawn", 27, Power::Offense,
            Condition::AfterKill, Profile::Caster, 11, 0, 0, 0 },
        { "Golden Pilgrim Sandals", 27, Power::Movement,
            Condition::Healthy, Profile::Caster, 8, 0, 10, 0 },
        { "Sunstone of the Burning Prayer", 27, Power::Signature,
            Condition::Always, Profile::Caster, 12, 500146, 12, 0 },
        { "Overclocked Gyroseal", 28, Power::Offense,
            Condition::Healthy, Profile::IntellectHybrid, 11, 0, 0, 0 },
        { "Runaway Clockwork Boots", 28, Power::Movement,
            Condition::OutOfCombat, Profile::IntellectHybrid, 8, 0, 15, 0 },
        { "Unstable Masterwork Core", 28, Power::Signature,
            Condition::Always, Profile::IntellectHybrid, 12, 801005, 12, 1 },
        { "Widow Queen Seal", 29, Power::Offense,
            Condition::Wounded, Profile::Caster, 11, 0, 0, 0 },
        { "Treads of the Molting Serpent", 29, Power::Movement,
            Condition::AfterKill, Profile::Caster, 8, 0, 18, 0 },
        { "Fang of the Thousand Venoms", 29, Power::Signature,
            Condition::Always, Profile::Caster, 12, 804961, 12, 12 },
        { "Harvest of the Forsaken", 30, Power::Offense,
            Condition::AfterKill, Profile::Agility, 11, 0, 0, 0 },
        { "Stride Beyond the Veil", 30, Power::Movement,
            Condition::Wounded, Profile::Agility, 8, 0, 20, 0 },
        { "Hourglass of the Last Breath", 30, Power::Signature,
            Condition::Always, Profile::Agility, 12, 800172, 12, 12 },
        { "Oath of the First Wild", 31, Power::Offense,
            Condition::Healthy, Profile::AgilityHybrid, 11, 0, 0, 0 },
        { "Trail of the Elder Beast", 31, Power::Movement,
            Condition::Healthy, Profile::AgilityHybrid, 8, 0, 10, 0 },
        { "Heart of the Broken Mountain", 31, Power::Signature,
            Condition::Always, Profile::AgilityHybrid, 12, 300693, 12, 2 },
        { "Seal of the Living Rune", 32, Power::Offense,
            Condition::Wounded, Profile::Caster, 11, 0, 0, 0 },
        { "Boots of the Shifting Glyph", 32, Power::Movement,
            Condition::OutOfCombat, Profile::Caster, 8, 0, 15, 0 },
        { "Tablet of the Unmaking Word", 32, Power::Signature,
            Condition::Always, Profile::Caster, 12, 801179, 12, 10 },
        { "Mantle of the Unbroken", 0, Power::Armor,
            Condition::Wounded, Profile::Universal, 16, 0, 20, 0 },
    }};
}

#endif
