-- Generated by tools/Generate-WitchHunterTonics.py; policy version 1.
-- Requires the reviewed Tonic scripts and metadata corrections.
START TRANSACTION;
DELETE FROM `spell_group` WHERE `id` = 1134;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1134, 680491),
(1134, 802276),
(1134, 802277),
(1134, 802278),
(1134, 802279),
(1134, 803535);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 1134;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`, `description`) VALUES
(1134, 2, '本地 CoA：只能激活一种巫猎手补剂');
DELETE FROM `spell_script_names` WHERE `spell_id` = -680491 AND `ScriptName` = 'spell_ascension_witch_hunter_dark_tonic';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802276 AND `ScriptName` = 'spell_ascension_witch_hunter_vampiric_tonic';
DELETE FROM `spell_script_names` WHERE `spell_id` = 802826 AND `ScriptName` = 'spell_ascension_witch_hunter_holy_water_tonic';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-680491, 'spell_ascension_witch_hunter_dark_tonic'),
(802276, 'spell_ascension_witch_hunter_vampiric_tonic'),
(802826, 'spell_ascension_witch_hunter_holy_water_tonic');
DELETE FROM `spell_proc` WHERE `SpellId` = 802276;
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(802276, 1, 0, 0, 0, 0, 332116, 1, 2, 0, 2, 6, 0, 100, 0, 0);
COMMIT;
