-- Generated by tools/Generate-TinkerAugmentations.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `spell_id` IN (653130, 653234, 653236, 653239, 653242, 653245) AND `ScriptName` = 'spell_ascension_tinker_augmentation';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653130, 'spell_ascension_tinker_augmentation'),
(653234, 'spell_ascension_tinker_augmentation'),
(653236, 'spell_ascension_tinker_augmentation'),
(653239, 'spell_ascension_tinker_augmentation'),
(653242, 'spell_ascension_tinker_augmentation'),
(653245, 'spell_ascension_tinker_augmentation');
DELETE FROM `spell_script_names` WHERE `spell_id` IN (653268, 653276, 653238, 653274) AND `ScriptName` = 'spell_ascension_tinker_augmentation_damage';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653268, 'spell_ascension_tinker_augmentation_damage'),
(653276, 'spell_ascension_tinker_augmentation_damage'),
(653238, 'spell_ascension_tinker_augmentation_damage'),
(653274, 'spell_ascension_tinker_augmentation_damage');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653247 AND `ScriptName` = 'spell_ascension_tinker_tracer';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653247, 'spell_ascension_tinker_tracer');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653247 AND `ScriptName` = 'aura_ascension_tinker_tracer';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653247, 'aura_ascension_tinker_tracer');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653240 AND `ScriptName` = 'aura_ascension_tinker_stim';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(653240, 'aura_ascension_tinker_stim');
DELETE FROM `spell_bonus_data` WHERE `entry` IN (653268, 653276, 653238, 653274, 653247);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(653268, 0, 0, 0, 0, '本地 CoA 穿刺强化：启动脚本中 11% 远程攻击强度，无法术强度'),
(653276, 0.1, 0, 0, 0, '本地 CoA 魔法强化：启动脚本中 10% 法术强度和 4.5% 远程攻击强度'),
(653238, 0.25, 0, 0, 0, '本地 CoA 爆炸强化：启动脚本中 25% 火焰法术强度和 10% 远程攻击强度'),
(653274, 0.155, 0, 0, 0, '本地 CoA 以太强化：15.5% 奥术法术强度'),
(653247, 0, 0.15, 0, 0, '本地 CoA 追踪强化：施法脚本中 15% 火焰法术强度（带 scalingbp）和 8% 远程攻击强度');
DELETE FROM `spell_proc` WHERE `SpellId` IN (653232, 653235, 653237, 653243, 653246, 653240);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(653232, 0, 0, 0, 0, 0, 320, 1, 2, 3, 0, 3, 0, 100, 0, 0),
(653235, 0, 0, 0, 0, 0, 320, 1, 2, 3, 0, 3, 0, 100, 0, 0),
(653237, 0, 0, 0, 0, 0, 320, 1, 2, 3, 0, 0, 0, 100, 1000, 0),
(653243, 0, 0, 0, 0, 0, 320, 1, 2, 3, 0, 6, 0, 100, 0, 0),
(653246, 0, 0, 0, 0, 0, 320, 1, 2, 3, 0, 0, 0, 100, 0, 0),
(653240, 0, 0, 0, 0, 0, 17408, 2, 2, 3, 0, 0, 0, 100, 0, 0);
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` = 653232 AND `spell_effect` = 653275 AND `type` = 2;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(653232, 653275, 2, '本地 CoA 以太强化：装备时减少魔法伤害');
COMMIT;
