-- Barbarian completion. Generated by tools/Generate-BarbarianCompletion.py.
DELETE FROM `spell_proc` WHERE `SpellId` IN (707389, 300499, 561360, 561397, 800131, 560880, 705240, 804745, 805893, 560939, 712673, 805811, 706354, 705158, 705214, 704240, 801549, 560364, 520539, 805997, 705238, 560450, 573256, 705162, 800943, 807861, 805804, 801782, 706804, 705211, 560586, 561332, 706821, 805821, 500061, 801759, 803499, 804141, 707764, 712468, 805780, 573064, 573224, 573225, 573077);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(707389, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(300499, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(561360, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(561397, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(800131, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 100, 0, 0),
(560880, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(705240, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(804745, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(805893, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(560939, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(712673, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(805811, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(706354, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(705158, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(705214, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(704240, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(801549, 0, 0, 0, 0, 0, 139944, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(560364, 0, 0, 0, 0, 0, 139944, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(520539, 0, 0, 0, 0, 0, 20, 1, 2, 9283, 2, 0, 0, 8, 0, 0),
(805997, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(705238, 0, 0, 0, 0, 0, 332116, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(560450, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(573256, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(705162, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(800943, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 2000, 0),
(807861, 0, 0, 0, 0, 0, 69974, 0, 2, 9283, 2, 0, 0, 100, 0, 0),
(805804, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(801782, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 25, 0, 0),
(706804, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 25, 0, 0),
(705211, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 1000, 0),
(560586, 0, 0, 0, 0, 0, 332116, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(561332, 0, 0, 0, 0, 0, 332116, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(706821, 0, 0, 0, 0, 0, 20, 1, 2, 9283, 2, 0, 0, 15, 0, 0),
(805821, 0, 0, 0, 0, 0, 664232, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(500061, 0, 0, 0, 0, 0, 559104, 2, 2, 9283, 2, 0, 0, 100, 0, 0),
(801759, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(803499, 0, 0, 0, 0, 0, 332116, 1, 2, 2, 2, 0, 0, 100, 0, 0),
(804141, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 100, 0, 0),
(707764, 0, 0, 0, 0, 0, 139944, 1, 2, 9283, 2, 0, 0, 30, 0, 0),
(712468, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 100, 0, 0),
(805780, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 10),
(573064, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 10),
(573224, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 10),
(573225, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 10),
(573077, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 2, 0, 0, 100, 0, 10);
DELETE FROM `spell_script_names` WHERE `spell_id` = 300499 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (300499, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 300870 AND `ScriptName` = 'aura_ascension_barbarian_bleed';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (300870, 'aura_ascension_barbarian_bleed');
DELETE FROM `spell_script_names` WHERE `spell_id` = 355562 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (355562, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500002 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500002, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500061 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500061, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500450 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500450, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500451 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500451, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500452 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500452, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500453 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500453, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500534 AND `ScriptName` = 'spell_ascension_barbarian_conversion';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500534, 'spell_ascension_barbarian_conversion');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500913 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500913, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500915 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500915, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500919 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500919, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500984 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500984, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500996 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500996, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500997 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500997, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500998 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500998, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500999 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500999, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501000 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501000, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501001 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501001, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501002 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501002, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501003 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501003, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501004 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501004, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501005 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501005, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501006 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501006, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501007 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501007, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501008 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501008, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501009 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501009, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501010 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501010, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501011 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501011, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503088 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503088, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503089 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503089, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503090 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503090, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503091 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503091, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503092 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503092, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503093 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503093, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504912 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504912, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504913 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504913, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504914 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504914, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504915 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504915, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504916 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504916, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 520539 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (520539, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 524675 AND `ScriptName` = 'spell_ascension_barbarian_conversion';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (524675, 'spell_ascension_barbarian_conversion');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560364 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560364, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560450 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560450, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560521 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560521, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560586 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560586, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560880 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560880, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560933 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560933, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560939 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560939, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 561332 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (561332, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 561360 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (561360, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 561397 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (561397, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572330 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572330, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572331 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572331, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573064 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573064, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573064 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573064, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573077 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573077, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573224 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573224, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573224 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573224, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573225 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573225, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573225 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573225, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573256 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573256, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 704240 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (704240, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705158 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705158, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705162 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705162, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705198 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705198, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705211 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705211, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705214 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705214, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705238 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705238, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705240 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705240, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706354 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706354, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706487 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706487, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706804 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706804, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706821 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706821, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707389 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707389, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707410 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707410, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707584 AND `ScriptName` = 'aura_ascension_barbarian_volley';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707584, 'aura_ascension_barbarian_volley');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707660 AND `ScriptName` = 'spell_ascension_barbarian_conversion';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707660, 'spell_ascension_barbarian_conversion');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707763 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707763, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707764 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707764, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707764 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707764, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707775 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707775, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 712467 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (712467, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 712468 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (712468, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 712468 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (712468, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 712673 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (712673, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 782801 AND `ScriptName` = 'aura_ascension_barbarian_bleed';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (782801, 'aura_ascension_barbarian_bleed');
DELETE FROM `spell_script_names` WHERE `spell_id` = 783054 AND `ScriptName` = 'aura_ascension_barbarian_bleed';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (783054, 'aura_ascension_barbarian_bleed');
DELETE FROM `spell_script_names` WHERE `spell_id` = 800131 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800131, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 800637 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800637, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 800943 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800943, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801549 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801549, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801759 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801759, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801761 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801761, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801782 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801782, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803499 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803499, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804141 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804141, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804141 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804141, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804745 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804745, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805780 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805780, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805780 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805780, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805785 AND `ScriptName` = 'spell_ascension_barbarian_conversion';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805785, 'spell_ascension_barbarian_conversion');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805804 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805804, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805804 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805804, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805808 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805808, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805811 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805811, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805821 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805821, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805832 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805832, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805893 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805893, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805997 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805997, 'aura_ascension_barbarian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806801 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806801, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806802 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806802, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806803 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806803, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806804 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806804, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806805 AND `ScriptName` = 'spell_ascension_barbarian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806805, 'spell_ascension_barbarian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806882 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806882, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806883 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806883, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806884 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806884, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806885 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806885, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806886 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806886, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 806887 AND `ScriptName` = 'aura_ascension_barbarian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (806887, 'aura_ascension_barbarian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807482 AND `ScriptName` = 'aura_ascension_barbarian_volley';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (807482, 'aura_ascension_barbarian_volley');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807861 AND `ScriptName` = 'aura_ascension_barbarian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (807861, 'aura_ascension_barbarian_event');
DELETE FROM `spell_bonus_data` WHERE `entry` IN (800152, 560932, 255846, 804143, 783054, 782801, 300870, 707660, 524675, 500534, 805785);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(800152, 0, 0, 1.2, 0, '野蛮人完成'),
(560932, 0, 0, 0.3, 0, '野蛮人完成'),
(255846, 0, 0, 0, 0, '野蛮人完成'),
(804143, 0, 0, 0, 0, '野蛮人完成'),
(783054, 0, 0, 0, 0, '野蛮人完成'),
(782801, 0, 0, 0, 0, '野蛮人完成'),
(300870, 0, 0, 0, 0, '野蛮人完成'),
(707660, 0, 0, 0, 0, '野蛮人完成'),
(524675, 0, 0, 0, 0, '野蛮人完成'),
(500534, 0, 0, 0, 0, '野蛮人完成'),
(805785, 0, 0, 0, 0, '野蛮人完成');
DELETE FROM `spell_group` WHERE `id` = 2000181 AND `spell_id` = 560821;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES (2000181, 560821);
DELETE FROM `spell_group` WHERE `id` = 2000182 AND `spell_id` = 560946;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES (2000182, 560946);
