-- Generated by Tools/Generate-GuardianStandards.py; no official server templates available.
-- Display IDs are client-evidenced. Neutral template/geometry defaults are local compatibility policy.
-- Install with Guardian runtime and matching patch-T; no spawns, loot or character mutations.
START TRANSACTION;
DELETE FROM `creature_template_model` WHERE `CreatureID` IN (50053, 50055, 50057, 50153, 60057, 60058, 60059, 60060, 60061, 60062, 60063, 60064, 60065, 220871);
DELETE FROM `creature_template` WHERE `entry` IN (50053, 50055, 50057, 50153, 60057, 60058, 60059, 60060, 60061, 60062, 60063, 60064, 60065, 220871);
INSERT INTO `creature_template` (`entry`, `name`, `minlevel`, `maxlevel`, `faction`, `unit_class`, `type`, `BaseAttackTime`, `RangeAttackTime`, `ScriptName`) VALUES
(50053, '恢复旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(50055, '集结旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(50057, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(50153, '力量旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60057, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60058, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60059, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60060, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60061, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60062, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60063, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60064, '英勇旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(60065, '霸权旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard'),
(220871, '法术防护旌旗', 1, 1, 35, 1, 11, 2000, 2000, 'npc_ascension_guardian_standard');
DELETE FROM `creature_template_model` WHERE `CreatureID` IN (50053, 50055, 50057, 50153, 60057, 60058, 60059, 60060, 60061, 60062, 60063, 60064, 60065, 220871);
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`) VALUES
(50053, 0, 147833, 1, 1),
(50055, 0, 147834, 1, 1),
(50057, 0, 148834, 1, 1),
(50153, 0, 147832, 1, 1),
(60057, 0, 148834, 1, 1),
(60058, 0, 148834, 1, 1),
(60059, 0, 148834, 1, 1),
(60060, 0, 148834, 1, 1),
(60061, 0, 148834, 1, 1),
(60062, 0, 148834, 1, 1),
(60063, 0, 148834, 1, 1),
(60064, 0, 148834, 1, 1),
(60065, 0, 148833, 1, 1),
(220871, 0, 147831, 1, 1);
DELETE FROM `creature_model_info` WHERE `DisplayID` IN (147831, 147832, 147833, 147834, 148833, 148834);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `Gender`) VALUES
(147831, 0.5, 1, 2),
(147832, 0.5, 1, 2),
(147833, 0.5, 1, 2),
(147834, 0.5, 1, 2),
(148833, 0.5, 1, 2),
(148834, 0.5, 1, 2);
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('aura_ascension_guardian_recovery', 'aura_ascension_guardian_tower', 'aura_ascension_guardian_valiance', 'spell_ascension_guardian_reclaim', 'spell_ascension_guardian_standard');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(500260, 'spell_ascension_guardian_standard'),
(500263, 'spell_ascension_guardian_standard'),
(500266, 'aura_ascension_guardian_recovery'),
(500547, 'spell_ascension_guardian_standard'),
(501538, 'aura_ascension_guardian_valiance'),
(501539, 'aura_ascension_guardian_valiance'),
(501540, 'aura_ascension_guardian_valiance'),
(501541, 'aura_ascension_guardian_valiance'),
(501542, 'aura_ascension_guardian_valiance'),
(501543, 'aura_ascension_guardian_valiance'),
(501544, 'aura_ascension_guardian_valiance'),
(501545, 'aura_ascension_guardian_valiance'),
(706805, 'spell_ascension_guardian_standard'),
(800315, 'aura_ascension_guardian_valiance'),
(800317, 'aura_ascension_guardian_tower'),
(800319, 'spell_ascension_guardian_standard'),
(800346, 'spell_ascension_guardian_standard'),
(801504, 'spell_ascension_guardian_reclaim'),
(803931, 'spell_ascension_guardian_standard'),
(803932, 'spell_ascension_guardian_standard'),
(803933, 'spell_ascension_guardian_standard'),
(803934, 'spell_ascension_guardian_standard'),
(803935, 'spell_ascension_guardian_standard'),
(803936, 'spell_ascension_guardian_standard'),
(803937, 'spell_ascension_guardian_standard'),
(803938, 'spell_ascension_guardian_standard');
DELETE FROM `spell_bonus_data` WHERE `entry` IN (500248, 800335);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(500248, 0, 0, 0, 0, '本地守护者恢复：光环脚本中使用明确的所有者力量'),
(800335, 0, 0, 0, 0, '本地守护者英勇：光环脚本中使用明确的所有者攻击强度');
COMMIT;
