-- Generated by tools/Generate-AlliedBuffExclusivity.py; policy version1.
START TRANSACTION;
DELETE FROM `spell_group` WHERE `id` = 1135;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1135, 572391),
(1135, 572396),
(1135, 801523),
(1135, 680307);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 1135;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`, `description`) VALUES
(1135, 2, '本地 CoA：每个施法者在每个接受者身上只能应用一个时空法师智慧');
DELETE FROM `spell_group` WHERE `id` = 1136;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1136, 706742),
(1136, 680315),
(1136, 803658),
(1136, 803665);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 1136;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`, `description`) VALUES
(1136, 2, '本地 CoA：每个施法者在每个接受者身上只能应用一个修补匠模块');
COMMIT;
