-- Guardian remaining mechanics. Generated by tools/Generate-GuardianCompletion.py.
DELETE FROM `spell_proc` WHERE `SpellId` IN (706807, 705379, 524694, 804891, 801121, 505202, 582901, 653386, 653410, 653281, 707137, 706514, 803432, 804383, 300927, 707170, 802188, 504910, 560093, 503634, 803524, 570759, 801774, 524932, 520651, 653303, 706637, 707372, 803126, 705351, 705377, 801778);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(706807, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(705379, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(524694, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 0, 0, 0, 50, 0, 0),
(804891, 0, 0, 0, 0, 0, 664232, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(801121, 0, 0, 0, 0, 0, 664232, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(505202, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 2, 0, 0, 25, 0, 0),
(582901, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 100, 1000, 0),
(653386, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 30, 0, 0),
(653410, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 30, 0, 0),
(653281, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 30, 5000, 0),
(707137, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 100, 0, 0),
(706514, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 100, 500, 0),
(803432, 0, 0, 0, 0, 0, 40, 1, 2, 8256, 0, 0, 0, 100, 0, 5),
(804383, 0, 0, 0, 0, 0, 44, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(300927, 0, 0, 0, 0, 0, 139944, 1, 2, 11331, 2, 0, 0, 100, 0, 0),
(707170, 0, 0, 0, 0, 0, 40, 1, 2, 16383, 0, 0, 0, 100, 0, 1),
(802188, 0, 0, 0, 0, 0, 40, 1, 2, 16383, 0, 0, 0, 100, 0, 5),
(504910, 0, 0, 0, 0, 0, 40, 1, 2, 16383, 0, 0, 0, 100, 0, 1),
(560093, 0, 0, 0, 0, 0, 40, 1, 2, 52, 0, 0, 0, 100, 1000, 0),
(503634, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(803524, 0, 0, 0, 0, 0, 332116, 1, 2, 9283, 2, 0, 0, 5, 0, 0),
(570759, 0, 0, 0, 0, 0, 332116, 1, 2, 9283, 2, 0, 0, 100, 0, 5),
(801774, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 0, 0, 0, 100, 0, 0),
(524932, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 0, 0, 0, 20, 0, 0),
(520651, 0, 0, 0, 0, 0, 20, 1, 2, 9283, 0, 0, 0, 100, 0, 3),
(653303, 0, 0, 0, 0, 0, 69972, 1, 2, 9283, 0, 0, 0, 100, 0, 1),
(706637, 0, 0, 0, 0, 0, 4, 1, 2, 9283, 0, 0, 0, 25, 0, 0),
(707372, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 100, 5000, 0),
(803126, 0, 0, 0, 0, 0, 20, 1, 2, 2, 0, 0, 0, 50, 0, 0),
(705351, 0, 0, 0, 0, 0, 69972, 1, 2, 2, 0, 0, 0, 100, 0, 0);
DELETE FROM `spell_script_names` WHERE `spell_id` = 300542 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (300542, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 300860 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (300860, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 300927 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (300927, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500170 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500170, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500258 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500258, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500463 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500463, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 500673 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (500673, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501068 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501068, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501069 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501069, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501070 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501070, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501071 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501071, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501072 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501072, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501073 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501073, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 501074 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (501074, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503119 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503119, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503120 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503120, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503121 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503121, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503122 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503122, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503123 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503123, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503124 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503124, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503125 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503125, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503126 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503126, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503344 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503344, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503345 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503345, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503346 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503346, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503347 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503347, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503348 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503348, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503349 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503349, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503350 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503350, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503351 AND `ScriptName` = 'aura_ascension_guardian_advance';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503351, 'aura_ascension_guardian_advance');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503634 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503634, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 503634 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (503634, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504139 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504139, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504177 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504177, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504178 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504178, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504179 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504179, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504180 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504180, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504181 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504181, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504182 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504182, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 504910 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (504910, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 505199 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (505199, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 505202 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (505202, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 520651 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (520651, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 524091 AND `ScriptName` = 'spell_ascension_guardian_converted_damage';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (524091, 'spell_ascension_guardian_converted_damage');
DELETE FROM `spell_script_names` WHERE `spell_id` = 524610 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (524610, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 524694 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (524694, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 524932 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (524932, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 560093 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (560093, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 570759 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (570759, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572142 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572142, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572143 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572143, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572144 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572144, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572145 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572145, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572146 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572146, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572147 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572147, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 572904 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (572904, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573204 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573204, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573205 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573205, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573206 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573206, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573207 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573207, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573208 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573208, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573209 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573209, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573210 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573210, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573211 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573211, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573275 AND `ScriptName` = 'spell_ascension_guardian_converted_damage';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573275, 'spell_ascension_guardian_converted_damage');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573286 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573286, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 573292 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (573292, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 574340 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (574340, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 575831 AND `ScriptName` = 'spell_ascension_guardian_converted_damage';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (575831, 'spell_ascension_guardian_converted_damage');
DELETE FROM `spell_script_names` WHERE `spell_id` = 582901 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (582901, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653281 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (653281, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653303 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (653303, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653386 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (653386, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 653410 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (653410, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705376 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705376, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705379 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705379, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705380 AND `ScriptName` = 'aura_ascension_guardian_converted_bleed';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705380, 'aura_ascension_guardian_converted_bleed');
DELETE FROM `spell_script_names` WHERE `spell_id` = 705381 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (705381, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706514 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706514, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706514 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706514, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706807 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706807, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 706808 AND `ScriptName` = 'aura_ascension_guardian_converted_bleed';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (706808, 'aura_ascension_guardian_converted_bleed');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707137 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707137, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707170 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707170, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 707662 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (707662, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 800311 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800311, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 800316 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (800316, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801121 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801121, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801774 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801774, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801774 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801774, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 801776 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (801776, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802188 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802188, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802284 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802284, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802439 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802439, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802440 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802440, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802441 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802441, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802442 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802442, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802443 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802443, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802629 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802629, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802739 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802739, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802740 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802740, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802741 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802741, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802742 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802742, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802743 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802743, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802744 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802744, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 802871 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (802871, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803129 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803129, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803130 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803130, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803432 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803432, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803524 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803524, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803683 AND `ScriptName` = 'spell_ascension_guardian_drums';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803683, 'spell_ascension_guardian_drums');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803738 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803738, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803956 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803956, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 803963 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (803963, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804383 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804383, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804691 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804691, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804891 AND `ScriptName` = 'aura_ascension_guardian_event';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804891, 'aura_ascension_guardian_event');
DELETE FROM `spell_script_names` WHERE `spell_id` = 804891 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (804891, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 805150 AND `ScriptName` = 'spell_ascension_guardian_ability';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (805150, 'spell_ascension_guardian_ability');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807297 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (807297, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_script_names` WHERE `spell_id` = 807794 AND `ScriptName` = 'aura_ascension_guardian_lifecycle';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (807794, 'aura_ascension_guardian_lifecycle');
DELETE FROM `spell_bonus_data` WHERE `entry` IN (803131, 802874, 500673, 520651, 706808, 705380, 524091, 575831, 573275);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(803131, 0, 0, 0.06, 0, '守护者完成'),
(802874, 0, 0, 0, 0.2575, '守护者完成'),
(500673, 0, 0, 0.1, 0, '守护者完成'),
(520651, 0, 0, 0, 0, '守护者完成'),
(706808, 0, 0, 0, 0, '守护者完成'),
(705380, 0, 0, 0, 0, '守护者完成'),
(524091, 0, 0, 0, 0, '守护者完成'),
(575831, 0, 0, 0, 0, '守护者完成'),
(573275, 0, 0, 0, 0, '守护者完成');
-- New template only; never replace an existing object definition.
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `size`, `ScriptName`)
SELECT 9000117, 5, 7217, '战鼓', 1, 'go_ascension_guardian_drum'
WHERE NOT EXISTS (SELECT 1 FROM `gameobject_template` WHERE `entry` = 9000117);
DELETE FROM `spell_group` WHERE `id` = 2000180;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(2000180, 19506),
(2000180, 30802),
(2000180, 53137),
(2000180, 300871),
(2000180, 524854),
(2000180, 560001),
(2000180, 560531),
(2000180, 560550),
(2000180, 560593),
(2000180, 704994),
(2000180, 706633),
(2000180, 712367),
(2000180, 804730);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 2000180;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES (2000180, 3);
DELETE FROM `spell_group` WHERE `id` = 2000181;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(2000181, 24907),
(2000181, 24932),
(2000181, 29801),
(2000181, 51466),
(2000181, 300565),
(2000181, 300873),
(2000181, 300877),
(2000181, 300879),
(2000181, 300889),
(2000181, 300958),
(2000181, 300968),
(2000181, 301974),
(2000181, 500264),
(2000181, 520372),
(2000181, 560533),
(2000181, 560535),
(2000181, 560539),
(2000181, 560568),
(2000181, 680709),
(2000181, 800031);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 2000181;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES (2000181, 3);
DELETE FROM `spell_group` WHERE `id` = 2000182;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(2000182, 2895),
(2000182, 50170),
(2000182, 53379),
(2000182, 300872),
(2000182, 300874),
(2000182, 300875),
(2000182, 300876),
(2000182, 300957),
(2000182, 300959),
(2000182, 503707),
(2000182, 560525),
(2000182, 560526),
(2000182, 560527),
(2000182, 560537),
(2000182, 560540),
(2000182, 560541),
(2000182, 560542),
(2000182, 560549),
(2000182, 560628),
(2000182, 567572),
(2000182, 680476),
(2000182, 704644),
(2000182, 705031),
(2000182, 706632),
(2000182, 800517),
(2000182, 800704),
(2000182, 804022),
(2000182, 804257),
(2000182, 804731);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 2000182;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES (2000182, 3);
DELETE FROM `spell_group` WHERE `id` = 2000183;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(2000183, 6562),
(2000183, 28878),
(2000183, 500069),
(2000183, 504159),
(2000183, 504787),
(2000183, 704632),
(2000183, 803511),
(2000183, 805443),
(2000183, 805888);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 2000183;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`) VALUES (2000183, 3);
