-- Spell target/cast conditions copied onto the Heroic/Mythic tiers of each spell (SpellDifficulty.dbc).
-- Generated by dungeon-recherche/stufen_bedingungen.py; tiers that already have own conditions are left alone.
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (13, 17) AND `SourceEntry` IN (74322, 151059, 151301, 151326, 152417, 161584, 350041, 350104, 350168, 350169, 350421, 350422, 378410, 378652, 378677, 379768, 388935);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 1, 151059, 0, 0, 31, 0, 3, 16062, 0, 1, 0, 0, '', 'Potential target of the spell is not creature, entry is 16062'),
(13, 1, 378410, 0, 0, 31, 0, 3, 16062, 0, 1, 0, 0, '', 'Potential target of the spell is not creature, entry is 16062'),
(13, 1, 161584, 0, 0, 31, 0, 3, 12057, 0, 0, 0, 0, '', 'Frenzy (SERVERSIDE) - should target only Garr'),
(13, 1, 388935, 0, 0, 31, 0, 3, 12057, 0, 0, 0, 0, '', 'Frenzy (SERVERSIDE) - should target only Garr'),
(13, 1, 350104, 0, 0, 31, 0, 3, 11663, 0, 0, 0, 0, '', 'Damage Shield targets Flamewaker Healer'),
(13, 1, 350104, 0, 1, 31, 0, 3, 11664, 0, 0, 0, 0, '', 'Damage Shield  targets Flamewaker Elite'),
(13, 1, 350168, 0, 0, 31, 0, 3, 14601, 0, 0, 0, 0, '', NULL),
(13, 1, 350169, 0, 0, 31, 0, 3, 14601, 0, 0, 0, 0, '', NULL),
(13, 1, 350041, 0, 0, 31, 0, 3, 11380, 0, 0, 0, 0, '', 'Powerful Healing Ward - Jin''do the Hexxer'),
(13, 1, 350421, 0, 0, 31, 0, 3, 14834, 0, 0, 0, 0, '', NULL),
(13, 1, 350422, 0, 0, 31, 0, 3, 14834, 0, 0, 0, 0, '', NULL),
(13, 3, 151301, 0, 0, 31, 0, 3, 3976, 0, 0, 0, 0, '', 'Target Scarlet Commander Mograine'),
(13, 3, 378652, 0, 0, 31, 0, 3, 3976, 0, 0, 0, 0, '', 'Target Scarlet Commander Mograine'),
(13, 3, 151326, 0, 0, 31, 0, 3, 3977, 0, 0, 0, 0, '', 'Target High Inquisitor Whitemane'),
(13, 3, 378677, 0, 0, 31, 0, 3, 3977, 0, 0, 0, 0, '', 'Target High Inquisitor Whitemane'),
(13, 7, 152417, 0, 0, 31, 0, 3, 6225, 0, 0, 0, 0, '', NULL),
(13, 7, 379768, 0, 0, 31, 0, 3, 6225, 0, 0, 0, 0, '', NULL),
(13, 7, 152417, 0, 1, 31, 0, 3, 6226, 0, 0, 0, 0, '', NULL),
(13, 7, 379768, 0, 1, 31, 0, 3, 6226, 0, 0, 0, 0, '', NULL),
(13, 7, 152417, 0, 2, 31, 0, 3, 6227, 0, 0, 0, 0, '', NULL),
(13, 7, 379768, 0, 2, 31, 0, 3, 6227, 0, 0, 0, 0, '', NULL),
(13, 7, 74322, 0, 0, 31, 0, 3, 36597, 0, 0, 0, 0, '', 'Harvested Soul - target The Lich King');
