-- Generated by tools/Generate-WitchHunterStake.py; policy version 1.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` IN (680537);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(680537, 0, 0, 0.675, 0, '本地 CoA 木桩：67.5% 近战攻击强度，无法术强度');
DELETE FROM `spell_script_names` WHERE `spell_id` IN (-680537) AND `ScriptName` = 'spell_ascension_witch_hunter_stake';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(-680537, 'spell_ascension_witch_hunter_stake');
DELETE FROM `spell_custom_attr` WHERE `spell_id` IN (680537, 681347, 681348, 681349, 681350, 681351, 681352);
INSERT INTO `spell_custom_attr` (`spell_id`, `attributes`) VALUES
(680537, 32768),
(681347, 32768),
(681348, 32768),
(681349, 32768),
(681350, 32768),
(681351, 32768),
(681352, 32768);
DELETE FROM `spell_proc` WHERE `SpellId` IN (680540);
INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES
(680540, 0, 21, 0, 134217728, 131072, 16, 7, 4, 12287, 0, 0, 0, 100, 0, 0);
COMMIT;
