-- On Darkmoon - Season 10 Wildcard every dungeon and raid boss dropped Runes of Ascension (375250, party loot, so
-- each group member got the full amount): 25 or 50 in normal dungeons, 75 and 175 for Heroic bosses, 400-725 in
-- raids and 2500-7000 for the final raid bosses. Amounts are the 'Dropped by' list of item 375250 on
-- db.ascension.gg archived 2026-08-04 during the season, limited to level 63 creatures that exist here. The
-- server grants them on the kill because a loot stack holds at most 255.
-- Generated by apps/coa-wildcard/boss_marks.py.
DROP TABLE IF EXISTS `ascension_wildcard_boss_marks`;
CREATE TABLE `ascension_wildcard_boss_marks` (
  `CreatureEntry` INT UNSIGNED NOT NULL,
  `Amount` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CreatureEntry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `ascension_wildcard_boss_marks`;
INSERT INTO `ascension_wildcard_boss_marks` (`CreatureEntry`, `Amount`) VALUES
(639, 50), -- Edwin VanCleef
(1716, 50), -- Bazil Thredd
(1853, 50), -- Darkmaster Gandling
(2748, 50), -- Archaedas
(3975, 50), -- Herod
(3977, 50), -- High Inquisitor Whitemane
(4275, 50), -- Archmage Arugal
(4421, 50), -- Charlga Razorflank
(4543, 50), -- Bloodmage Thalnos
(4829, 50), -- Aku'mai
(5709, 50), -- Shade of Eranikus
(5775, 50), -- Verdan the Everliving
(6109, 250), -- Azuregos
(6487, 50), -- Arcanist Doan
(7267, 50), -- Chief Ukorz Sandscalp
(7358, 50), -- Amnennar the Coldbringer
(7800, 50), -- Mekgineer Thermaplugg
(8923, 50), -- Panzor the Invincible
(8983, 50), -- Golem Lord Argelmach
(9016, 50), -- Bael'Gar
(9017, 50), -- Lord Incendius
(9018, 50), -- High Interrogator Gerstahn
(9019, 50), -- Emperor Dagran Thaurissan
(9024, 50), -- Pyromancer Loregrain
(9025, 50), -- Lord Roccor
(9027, 50), -- Gorosh the Dervish
(9028, 50), -- Grizzle
(9029, 50), -- Eviscerator
(9030, 50), -- Ok'thor the Breaker
(9031, 50), -- Anub'shiah
(9032, 50), -- Hedrum the Creeper
(9033, 50), -- General Angerforge
(9041, 50), -- Warder Stilgiss
(9042, 25), -- Verek
(9056, 50), -- Fineous Darkvire
(9156, 50), -- Ambassador Flamelash
(9196, 50), -- Highlord Omokk
(9217, 50), -- Wizz'Magg the Magus
(9218, 50), -- Razmorg the Decapitator
(9219, 50), -- Chop'gog the Butcher
(9236, 50), -- Shadow Hunter Vosh'gajin
(9237, 50), -- War Master Voone
(9319, 50), -- Houndmaster Grebmar
(9437, 25), -- Dark Keeper Vorfalk
(9438, 25), -- Dark Keeper Bethek
(9439, 25), -- Dark Keeper Uggel
(9441, 25), -- Dark Keeper Zimrel
(9442, 25), -- Dark Keeper Ofgut
(9443, 25), -- Dark Keeper Pelver
(9476, 50), -- Watchman Doomgrip
(9499, 50), -- Plugger Spazzring
(9502, 50), -- Phalanx
(9537, 50), -- Hurley Blackbreath
(9543, 50), -- Ribbly Screwspigot
(9568, 50), -- Overlord Wyrmthalak
(9596, 50), -- Bannok Grimaxe
(9718, 50), -- Ghok Bashguud
(9736, 50), -- Quartermaster Zigris
(9816, 50), -- Pyroguard Emberseer
(9938, 50), -- Magmus
(10076, 25), -- High Priestess of Thaurissan
(10184, 4000), -- Onyxia
(10220, 50), -- Halycon
(10263, 50), -- Xot'hot the Burning
(10264, 50), -- Solakar Flamewreath
(10268, 50), -- Gizrul the Slavener
(10363, 50), -- General Drakkisath
(10376, 50), -- Crystal Fang
(10393, 50), -- Skul
(10429, 50), -- Warchief Rend Blackhand
(10430, 50), -- The Beast
(10432, 50), -- Vectus
(10433, 50), -- Marduk Blackpool
(10435, 50), -- Magistrate Barthilas
(10436, 50), -- Baroness Anastari
(10437, 50), -- Nerub'enkan
(10438, 50), -- Maleki the Pallid
(10439, 50), -- Ramstein the Gorger
(10440, 50), -- Baron Rivendare
(10502, 50), -- Lady Illucia Barov
(10503, 50), -- Jandice Barov
(10504, 50), -- Lord Alexei Barov
(10505, 50), -- Instructor Malicia
(10506, 50), -- Kirtonos the Herald
(10507, 50), -- The Ravenian
(10508, 50), -- Ras Frostwhisper
(10509, 50), -- Jed Runewatcher
(10516, 50), -- The Unforgiven
(10558, 50), -- Hearthsinger Forresten
(10584, 50), -- Urok Doomhowl
(10596, 50), -- Mother Smolderweb
(10808, 50), -- Timmy the Cruel
(10809, 50), -- Stonespine
(10811, 50), -- Archivist Galford
(10812, 25), -- Grand Crusader Dathrohan
(10813, 50), -- Balnazzar
(10899, 50), -- Goraluk Anvilcrack
(10901, 50), -- Lorekeeper Polkelt
(10997, 50), -- Cannon Master Willey
(11032, 50), -- Malor the Zealous
(11058, 50), -- Fras Siabi
(11082, 25), -- Stratholme Courier
(11120, 25), -- Crimson Hammersmith
(11121, 25), -- Black Guard Swordsmith
(11143, 25), -- Postmaster Malown
(11261, 50), -- Doctor Theolen Krastinov
(11380, 325), -- Jin'do the Hexxer
(11382, 325), -- Bloodlord Mandokir
(11467, 50), -- Tsu'zee
(11486, 50), -- Prince Tortheldrin
(11487, 50), -- Magister Kalendris
(11488, 50), -- Illyanna Ravenoak
(11489, 50), -- Tendris Warpwood
(11490, 50), -- Zevrim Thornhoof
(11492, 50), -- Alzzin the Wildshaper
(11496, 50), -- Immol'thar
(11501, 50), -- King Gordok
(11502, 3000), -- Ragnaros
(11520, 50), -- Taragaman the Hungerer
(11583, 4000), -- Nefarian
(11622, 50), -- Rattlegore
(11982, 400), -- Magmadar
(11983, 450), -- Firemaw
(11988, 400), -- Golemagg the Incinerator
(12017, 450), -- Broodlord Lashlayer
(12056, 400), -- Baron Geddon
(12057, 400), -- Garr
(12098, 400), -- Sulfuron Harbinger
(12118, 400), -- Lucifron
(12201, 50), -- Princess Theradras
(12236, 50), -- Lord Vyletongue
(12258, 50), -- Razorlash
(12259, 400), -- Gehennas
(12264, 400), -- Shazzrah
(12435, 450), -- Razorgore the Untamed
(13020, 450), -- Vaelastrasz the Corrupt
(13280, 50), -- Hydrospawn
(14020, 450), -- Chromaggus
(14321, 50), -- Guard Fengus
(14322, 50), -- Stomper Kreeg
(14323, 50), -- Guard Slip'kik
(14324, 50), -- Cho'Rush the Observer
(14325, 50), -- Captain Kromcrush
(14326, 50), -- Guard Mol'dar
(14327, 50), -- Lethtendris
(14354, 25), -- Pusillin
(14471, 250), -- Setis
(14506, 50), -- Lord Hel'nurath
(14507, 325), -- High Priest Venoxis
(14509, 325), -- High Priest Thekal
(14510, 325), -- High Priestess Mar'li
(14515, 325), -- High Priestess Arlokk
(14516, 50), -- Death Knight Darkreaver
(14517, 325), -- High Priestess Jeklik
(14834, 2500), -- Hakkar
(14861, 50), -- Blood Steward of Kirtonos
(14877, 325), -- High Priest Venoxis
(14941, 325), -- High Priestess Jeklik
(14966, 325), -- High Priest Thekal
(14967, 325), -- High Priestess Mar'li
(14968, 325), -- High Priestess Arlokk
(15082, 200), -- Gri'lek
(15083, 325), -- Hazza'rah
(15084, 325), -- Renataki
(15085, 325), -- Wushoolay
(15114, 325), -- Gahz'ranka
(15263, 525), -- The Prophet Skeram
(15275, 525), -- Emperor Vek'nilash
(15299, 525), -- Viscidus
(15339, 4000), -- Ossirian the Unscarred
(15340, 475), -- Moam
(15341, 475), -- General Rajaxx
(15348, 475), -- Kurinnaxx
(15369, 475), -- Ayamiss the Hunter
(15370, 475), -- Buru the Gorger
(15509, 525), -- Princess Huhuran
(15510, 525), -- Fankriss the Unyielding
(15511, 525), -- Lord Kri
(15516, 525), -- Battleguard Sartura
(15517, 525), -- Ouro
(15727, 4000), -- C'Thun
(15928, 550), -- Thaddius
(15931, 550), -- Grobbulus
(15932, 550), -- Gluth
(15936, 550), -- Heigan the Unclean
(15952, 550), -- Maexxna
(15953, 550), -- Grand Widow Faerlina
(15954, 550), -- Noth the Plaguebringer
(15956, 550), -- Anub'Rekhan
(15989, 550), -- Sapphiron
(15990, 5000), -- Kel'Thuzad
(16011, 550), -- Loatheb
(16028, 550), -- Patchwerk
(16042, 50), -- Lord Valthalak
(16059, 25), -- Theldren
(16060, 550), -- Gothik the Harvester
(16061, 550), -- Instructor Razuvious
(16062, 550), -- Highlord Mograine
(16080, 50), -- Mor Grayhoof
(16097, 50), -- Isalien
(16101, 25), -- Jarien
(16102, 25), -- Sothos
(16118, 50), -- Kormok
(17306, 50), -- Watchkeeper Gargolmar
(17307, 50), -- Vazruden the Herald
(17308, 50), -- Omor the Unscarred
(17377, 50), -- Keli'dan the Breaker
(17380, 50), -- Broggok
(17381, 50), -- The Maker
(24664, 50), -- Kael'thas Sunstrider
(29417, 250), -- Gluth - Heroic
(30549, 250), -- NOT SPAWNED - Baron Rivendare
(64600, 250), -- Setis
(64627, 250), -- Snowgrave
(67532, 250), -- Atal'zul, the Soulreaver
(110184, 5250), -- Onyxia - Heroic
(111502, 4000), -- Ragnaros - Heroic
(111982, 525), -- Magmadar - Heroic
(111988, 525), -- Golemagg the Incinerator - Heroic
(112056, 525), -- Baron Geddon - Heroic
(112057, 525), -- Garr - Heroic
(112098, 525), -- Sulfuron Harbinger - Heroic
(112118, 525), -- Lucifron - Heroic
(112259, 525), -- Gehennas - Heroic
(112264, 525), -- Shazzrah - Heroic
(210184, 7000); -- Onyxia - Mythic
