-- Generated by Tools/Generate-LocalClassStarters.py --write; do not edit.
-- Only local generated creation rosters change; existing characters and item templates are untouched.
START TRANSACTION;
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 12 AND `Note` = '飞升野蛮人起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 12, 2000000, 1, '飞升野蛮人起始套装'),
(0, 12, 2000001, 1, '飞升野蛮人起始套装'),
(0, 12, 2000002, 1, '飞升野蛮人起始套装'),
(0, 12, 12282, 1, '飞升野蛮人起始套装'),
(0, 12, 357876, 1, '飞升野蛮人起始套装'),
(0, 12, 6948, 1, '飞升野蛮人起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 13 AND `Note` = '飞升巫医起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 13, 2000011, 1, '飞升巫医起始套装'),
(0, 13, 484330, 1, '飞升巫医起始套装'),
(0, 13, 2000013, 1, '飞升巫医起始套装'),
(0, 13, 629945, 1, '飞升巫医起始套装'),
(0, 13, 2000014, 1, '飞升巫医起始套装'),
(0, 13, 6948, 1, '飞升巫医起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 14 AND `Note` = '飞升恶魔猎手起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 14, 2000007, 1, '飞升恶魔猎手起始套装'),
(0, 14, 2000008, 1, '飞升恶魔猎手起始套装'),
(0, 14, 2000009, 1, '飞升恶魔猎手起始套装'),
(0, 14, 629940, 1, '飞升恶魔猎手起始套装'),
(0, 14, 6948, 1, '飞升恶魔猎手起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 15 AND `Note` = '飞升巫猎手起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 15, 2000015, 1, '飞升巫猎手起始套装'),
(0, 15, 2000016, 1, '飞升巫猎手起始套装'),
(0, 15, 2000018, 1, '飞升巫猎手起始套装'),
(0, 15, 2092, 1, '飞升巫猎手起始套装'),
(0, 15, 2149641, 1, '飞升巫猎手起始套装'),
(0, 15, 2000017, 1, '飞升巫猎手起始套装'),
(0, 15, 6948, 1, '飞升巫猎手起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 16 AND `Note` = '飞升风暴使者起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 16, 2000019, 1, '飞升风暴使者起始套装'),
(0, 16, 2000020, 1, '飞升风暴使者起始套装'),
(0, 16, 2000021, 1, '飞升风暴使者起始套装'),
(0, 16, 682734, 1, '飞升风暴使者起始套装'),
(0, 16, 501973, 1, '飞升风暴使者起始套装'),
(0, 16, 6948, 1, '飞升风暴使者起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 17 AND `Note` = '飞升索洛斯骑士起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 17, 2000022, 1, '飞升索洛斯骑士起始套装'),
(0, 17, 2000023, 1, '飞升索洛斯骑士起始套装'),
(0, 17, 2000024, 1, '飞升索洛斯骑士起始套装'),
(0, 17, 629951, 1, '飞升索洛斯骑士起始套装'),
(0, 17, 6948, 1, '飞升索洛斯骑士起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 18 AND `Note` = '飞升守护者起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 18, 2000025, 1, '飞升守护者起始套装'),
(0, 18, 2000026, 1, '飞升守护者起始套装'),
(0, 18, 2000027, 1, '飞升守护者起始套装'),
(0, 18, 629951, 1, '飞升守护者起始套装'),
(0, 18, 629929, 1, '飞升守护者起始套装'),
(0, 18, 244613, 1, '飞升守护者起始套装'),
(0, 18, 6948, 1, '飞升守护者起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 19 AND `Note` = '飞升武僧起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 19, 2000028, 1, '飞升武僧起始套装'),
(0, 19, 2117000, 1, '飞升武僧起始套装'),
(0, 19, 2000030, 1, '飞升武僧起始套装'),
(0, 19, 629941, 1, '飞升武僧起始套装'),
(0, 19, 2446130, 1, '飞升武僧起始套装'),
(0, 19, 6948, 1, '飞升武僧起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 20 AND `Note` = '飞升阿鲁加之子起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 20, 2000031, 1, '飞升阿鲁加之子起始套装'),
(0, 20, 494334, 1, '飞升阿鲁加之子起始套装'),
(0, 20, 2000033, 1, '飞升阿鲁加之子起始套装'),
(0, 20, 629942, 1, '飞升阿鲁加之子起始套装'),
(0, 20, 6948, 1, '飞升阿鲁加之子起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 21 AND `Note` = '飞升游侠起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 21, 2000038, 1, '飞升游侠起始套装'),
(0, 21, 2000039, 1, '飞升游侠起始套装'),
(0, 21, 2000040, 1, '飞升游侠起始套装'),
(0, 21, 2092, 1, '飞升游侠起始套装'),
(0, 21, 484322, 1, '飞升游侠起始套装'),
(0, 21, 6948, 1, '飞升游侠起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 22 AND `Note` = '飞升时空法师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 22, 494335, 1, '飞升时空法师起始套装'),
(0, 22, 2000045, 1, '飞升时空法师起始套装'),
(0, 22, 2000046, 1, '飞升时空法师起始套装'),
(0, 22, 629948, 1, '飞升时空法师起始套装'),
(0, 22, 6948, 1, '飞升时空法师起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 23 AND `Note` = '飞升死灵法师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 23, 2000051, 1, '飞升死灵法师起始套装'),
(0, 23, 2000052, 1, '飞升死灵法师起始套装'),
(0, 23, 2000053, 1, '飞升死灵法师起始套装'),
(0, 23, 629950, 1, '飞升死灵法师起始套装'),
(0, 23, 6948, 1, '飞升死灵法师起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 24 AND `Note` = '飞升火焰法师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 24, 2000054, 1, '飞升火焰法师起始套装'),
(0, 24, 2000055, 1, '飞升火焰法师起始套装'),
(0, 24, 2000056, 1, '飞升火焰法师起始套装'),
(0, 24, 484327, 1, '飞升火焰法师起始套装'),
(0, 24, 6948, 1, '飞升火焰法师起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 25 AND `Note` = '飞升邪教徒起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 25, 2000057, 1, '飞升邪教徒起始套装'),
(0, 25, 484331, 1, '飞升邪教徒起始套装'),
(0, 25, 2000059, 1, '飞升邪教徒起始套装'),
(0, 25, 629982, 1, '飞升邪教徒起始套装'),
(0, 25, 6948, 1, '飞升邪教徒起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 26 AND `Note` = '飞升唤星者起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 26, 2000060, 1, '飞升唤星者起始套装'),
(0, 26, 2000061, 1, '飞升唤星者起始套装'),
(0, 26, 2000062, 1, '飞升唤星者起始套装'),
(0, 26, 2000004, 1, '飞升唤星者起始套装'),
(0, 26, 6948, 1, '飞升唤星者起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 27 AND `Note` = '飞升太阳牧师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 27, 2000063, 1, '飞升太阳牧师起始套装'),
(0, 27, 2000064, 1, '飞升太阳牧师起始套装'),
(0, 27, 2000065, 1, '飞升太阳牧师起始套装'),
(0, 27, 629944, 1, '飞升太阳牧师起始套装'),
(0, 27, 6948, 1, '飞升太阳牧师起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 28 AND `Note` = '飞升修补匠起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 28, 2000041, 1, '飞升修补匠起始套装'),
(0, 28, 2000042, 1, '飞升修补匠起始套装'),
(0, 28, 2000043, 1, '飞升修补匠起始套装'),
(0, 28, 2000048, 1, '飞升修补匠起始套装'),
(0, 28, 484364, 1, '飞升修补匠起始套装'),
(0, 28, 2000047, 1, '飞升修补匠起始套装'),
(0, 28, 6948, 1, '飞升修补匠起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 29 AND `Note` = '飞升毒法师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 29, 967757, 1, '飞升毒法师起始套装'),
(0, 29, 2000067, 1, '飞升毒法师起始套装'),
(0, 29, 2000068, 1, '飞升毒法师起始套装'),
(0, 29, 629982, 1, '飞升毒法师起始套装'),
(0, 29, 6948, 1, '飞升毒法师起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 30 AND `Note` = '飞升收割者起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 30, 2000069, 1, '飞升收割者起始套装'),
(0, 30, 2000070, 1, '飞升收割者起始套装'),
(0, 30, 2000071, 1, '飞升收割者起始套装'),
(0, 30, 2000005, 1, '飞升收割者起始套装'),
(0, 30, 2001095, 1, '飞升收割者起始套装'),
(0, 30, 6948, 1, '飞升收割者起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 31 AND `Note` = '飞升原始主义者起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 31, 2000072, 1, '飞升原始主义者起始套装'),
(0, 31, 2000073, 1, '飞升原始主义者起始套装'),
(0, 31, 2000074, 1, '飞升原始主义者起始套装'),
(0, 31, 629941, 1, '飞升原始主义者起始套装'),
(0, 31, 6948, 1, '飞升原始主义者起始套装');
DELETE FROM `playercreateinfo_item` WHERE `race` = 0 AND `class` = 32 AND `Note` = '飞升符文大师起始套装';
INSERT IGNORE INTO `playercreateinfo_item` (`race`, `class`, `itemid`, `amount`, `Note`) VALUES
(0, 32, 2000078, 1, '飞升符文大师起始套装'),
(0, 32, 2000079, 1, '飞升符文大师起始套装'),
(0, 32, 2000080, 1, '飞升符文大师起始套装'),
(0, 32, 629952, 1, '飞升符文大师起始套装'),
(0, 32, 511017, 1, '飞升符文大师起始套装'),
(0, 32, 6948, 1, '飞升符文大师起始套装');
-- Deprecated baseline grants: keep spell definitions and unrelated creation rows.
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 16384 AND `Spell` = 804657 AND `Note` LIKE 'Ascension %';
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 1048576 AND `Spell` = 804331 AND `Note` LIKE 'Ascension %';
DELETE FROM `playercreateinfo_spell_custom` WHERE `racemask` = 0 AND `classmask` = 134217728 AND `Spell` = 801711 AND `Note` LIKE 'Ascension %';
COMMIT;
