-- Generated by tools/Generate-ClassParityBatch1.py; policy version 1.
-- Deploy with the Ranger offensive-spell corrections in AscensionClassMechanics.cpp.
START TRANSACTION;
DELETE FROM `spell_bonus_data` WHERE `entry` IN (500075, 807237);
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(500075, 0, 0, 0.485, 0, '本地游侠：精准射击 明确远程攻击强度'),
(807237, 0, 0, 0, 0.1, '本地游侠：毒镖 明确远程攻击强度');
DELETE FROM `spell_group` WHERE `id` = 1127;
INSERT INTO `spell_group` (`id`, `spell_id`) VALUES
(1127, 574360),
(1127, 800510),
(1127, 801123),
(1127, 801128),
(1127, 802203),
(1127, 805356);
DELETE FROM `spell_group_stack_rules` WHERE `group_id` = 1127;
INSERT INTO `spell_group_stack_rules` (`group_id`, `stack_rule`, `description`) VALUES
(1127, 2, '本地唤星者：每个施法者只能激活一个守护');
COMMIT;
