-- Generated by tools/Generate-RunemasterBrand.py; source policy version1.
START TRANSACTION;
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_ascension_runemaster_brand', 'spell_ascension_runemaster_brand_runeblade');
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(712299, 'spell_ascension_runemaster_brand'),
(712301, 'spell_ascension_runemaster_brand'),
(712302, 'spell_ascension_runemaster_brand'),
(712303, 'spell_ascension_runemaster_brand'),
(712304, 'spell_ascension_runemaster_brand'),
(712305, 'spell_ascension_runemaster_brand'),
(712306, 'spell_ascension_runemaster_brand'),
(712307, 'spell_ascension_runemaster_brand'),
(573444, 'spell_ascension_runemaster_brand_runeblade'),
(573445, 'spell_ascension_runemaster_brand_runeblade'),
(573446, 'spell_ascension_runemaster_brand_runeblade'),
(573447, 'spell_ascension_runemaster_brand_runeblade'),
(707141, 'spell_ascension_runemaster_brand_runeblade'),
(707143, 'spell_ascension_runemaster_brand_runeblade'),
(707144, 'spell_ascension_runemaster_brand_runeblade'),
(707145, 'spell_ascension_runemaster_brand_runeblade'),
(707146, 'spell_ascension_runemaster_brand_runeblade'),
(707147, 'spell_ascension_runemaster_brand_runeblade'),
(707148, 'spell_ascension_runemaster_brand_runeblade');
DELETE FROM `spell_bonus_data` WHERE `entry` = 712324;
INSERT INTO `spell_bonus_data` (`entry`, `direct_bonus`, `dot_bonus`, `ap_bonus`, `ap_dot_bonus`, `comments`) VALUES
(712324, 0, 0, 0.185, 0, '飞升符文爆炸 - 可见的标记契约');
COMMIT;
