/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */

#include "CoAScriptLoader.h"
#include "AscensionReaperDirge.h"
#include "AscensionTinkerOverload.h"
#include "AscensionRunemasterGlyphs.h"
#include "AscensionManastorm.h"
#include "AscensionRunemasterBrand.h"
#include "AscensionRunemasterScaling.h"
#include "AscensionTinkerRockadier.h"
#include "AscensionRunemasterZenith.h"
#include "AscensionRunemasterEchoes.h"
#include "AscensionVenomancerVenoms.h"
#include "AscensionVenomancerVenomProcs.h"
#include "AscensionVenomancerVenomTalents.h"
#include "AscensionVenomancerVenomPayloads.h"
#include "AscensionTinkerCombatSymbiosis.h"

void AddAscensionCompatScripts();
void AddAscensionTravelPermitScripts();
void AddSC_AscensionRulesets();
void AddSC_AscensionMercenary();
void AddSC_AscensionHighRisk();
void AddSC_AscensionBloodforged();
void AddSC_AscensionPvpPower();
void AddSC_AscensionRestingBuff();
void AddSC_AscensionClosestResurrection();
void AddSC_AscensionThreatRedirect();
void AddSC_AscensionKeepersScrollSteadfast();
void AddSC_AscensionProfessionSpellAffect();
void AddSC_AscensionKeepersScrollZoneBuff();
void AddAscensionStockCoefficientScripts();
void AddAscensionScalingBaseScripts();
void AddCoABugReportScripts();
void AddCoAPlayerTicketScripts();
void AddAscensionAccountInfoScripts();
void AddCoAGameplayTestScripts();
void AddSC_AscensionResourceTalents();
void AddAscensionBarbarianCompletionScripts();
void AddAscensionBarbarianEventScripts();
void AddAscensionBarbarianAbilityScripts();
void AddAscensionGuardianStandardScripts();
void AddAscensionGuardianFavorScripts();
void AddAscensionGuardianEventScripts();
void AddAscensionGuardianCompletionScripts();
void AddAscensionGuardianAbilityScripts();
void AddAscensionGuardianTalentScripts();
void AddAscensionGuardianDrumScripts();
void AddAscensionRangerDamageScripts();
void AddAscensionRangerScalingScripts();
void AddAscensionRangerAssaultScripts();
void AddAscensionWitchHunterTonicScripts();
void AddAscensionWitchHunterTonicTalentScripts();
void AddAscensionWitchHunterTorchScripts();
void AddAscensionWitchHunterFlameScripts();
void AddAscensionWitchHunterTorchlightScripts();
void AddAscensionWitchHunterStakeScripts();
void AddAscensionWitchHunterCompletionScripts();
void AddAscensionWitchHunterEventScripts();
void AddAscensionWitchHunterAbilityScripts();
void AddAscensionWitchHunterDefenseScripts();
void AddAscensionWitchHunterSummonScripts();
void AddAscensionWitchDoctorCompletionScripts();
void AddAscensionWitchDoctorEventScripts();
void AddAscensionWitchDoctorAbilityScripts();
void AddAscensionWitchDoctorBrewingScripts();
void AddAscensionWitchDoctorAuraScripts();
void AddAscensionWitchDoctorSummonScripts();
void AddAscensionNecromancerScripts();
void AddAscensionNecromancerContractScripts();
void AddAscensionNecromancerSummonScripts();
void AddAscensionNecromancerEventScripts();
void AddAscensionNecromancerAbilityScripts();
void AddAscensionNecromancerAuraScripts();
void AddSC_AscensionXoroth();
void AddSC_AscensionStarcaller();
void AddSC_AscensionStarcallerContracts();
void AddSC_AscensionPyromancer();
void AddSC_AscensionPyromancerContracts();
void AddSC_AscensionPyromancerEvents();
void AddSC_AscensionPyromancerAbilities();
void AddSC_AscensionPyromancerAuras();
void AddSC_AscensionPyromancerSummons();
void AddSC_AscensionCultist();
void AddSC_AscensionCultistContracts();
void AddSC_AscensionCultistEvents();
void AddSC_AscensionCultistAbilities();
void AddSC_AscensionCultistAuras();
void AddSC_AscensionCultistSummons();
void AddSC_AscensionVenomancer();
void AddSC_AscensionVenomancerContracts();
void AddSC_AscensionVenomancerEvents();
void AddSC_AscensionVenomancerAbilities();
void AddSC_AscensionVenomancerAuras();
void AddSC_AscensionVenomancerSummons();
void AddSC_AscensionTinker();
void AddSC_AscensionTinkerContracts();
void AddSC_AscensionTinkerEvents();
void AddSC_AscensionTinkerAbilities();
void AddSC_AscensionTinkerAuras();
void AddSC_AscensionTinkerSummons();
void AddSC_AscensionSunCleric();
void AddSC_AscensionSunClericContracts();
void AddSC_AscensionSunClericEvents();
void AddSC_AscensionSunClericAbilities();
void AddSC_AscensionSunClericAuras();
void AddSC_AscensionSunClericSummons();
void AddSC_AscensionSunClericValkyrie();
void AddSC_AscensionSunClericDevotion();
void AddSC_AscensionSunClericRadiance();
void AddSC_AscensionStarcallerEvents();
void AddSC_AscensionStarcallerAbilities();
void AddSC_AscensionStarcallerAuras();
void AddSC_AscensionStarcallerMechanics();
void AddSC_AscensionXorothContracts();
void AddSC_AscensionXorothEvents();
void AddSC_AscensionXorothAbilities();
void AddSC_AscensionXorothAuras();
void AddSC_AscensionXorothSummons();
void AddSC_AscensionFelsworn();
void AddSC_AscensionFelswornContracts();
void AddSC_AscensionFelswornAuras();
void AddSC_AscensionFelswornEvents();
void AddSC_AscensionFelswornAbilities();
void AddSC_AscensionFelswornSummons();
void AddSC_AscensionTemplar();
void AddSC_AscensionTemplarContracts();
void AddSC_AscensionTemplarAuras();
void AddSC_AscensionTemplarEvents();
void AddSC_AscensionTemplarAbilities();
void AddSC_AscensionTemplarSummons();
void AddSC_AscensionTemplarTemporaryLibramProcs();
void AddSC_AscensionTemplarTithe();
void AddAscensionTinkerAugmentationScripts();
void AddAscensionTinkerAugmentationTalentScripts();
void AddAscensionTinkerHackingScripts();
void AddSC_AscensionPrimalistEarthshaping();
void AddSC_AscensionPrimalistHeavyEarth();
void AddSC_AscensionPrimalistEarthshaker();
void AddSC_AscensionPrimalistRunningInstinct();
void AddSC_AscensionPrimalistRideWave();
void AddSC_AscensionPrimalistPowerHammer();
void AddSC_AscensionPrimalistEmeraldWill();
void AddSC_AscensionPrimalistTotemicEchoes();
void AddSC_AscensionPrimalistWildCarnage();
void AddSC_AscensionPrimalistPendant();
void AddSC_AscensionPrimalistThorns();
void AddSC_AscensionPrimalistBloodyClaws();
void AddSC_AscensionPrimalistJudgement();
void AddSC_AscensionPrimalistShattering();
void AddSC_AscensionPrimalistPrecision();
void AddSC_AscensionPrimalistVerdantChase();
void AddSC_AscensionPrimalistJourney();
void AddSC_AscensionPrimalistQuakingThane();
void AddSC_AscensionPrimalistTremors();
void AddSC_AscensionPrimalistCataclysm();
void AddSC_AscensionPrimalistFaePresence();
void AddSC_AscensionPrimalistEarthsGuidance();
void AddSC_AscensionPrimalistGroveTender();
void AddSC_AscensionPrimalistBramblepatch();
void AddSC_AscensionPrimalistPrimalStrikes();
void AddSC_AscensionPrimalistLithicLance();
void AddSC_AscensionPrimalistEmpoweredBoons();
void AddSC_AscensionPrimalistEarthmotherWarden();
void AddSC_AscensionPrimalistDruidTraining();
void AddSC_AscensionPrimalistSpiritualFrenzy();
void AddSC_AscensionPrimalistPhysicalCrit();
void AddSC_AscensionPrimalistRipsAndTears();
void AddSC_AscensionPrimalistMountainAvatar();
void AddSC_AscensionPrimalistRylaksBite();
void AddSC_AscensionPrimalistRylaksBlessing();
void AddSC_AscensionPrimalistWildheart();
void AddSC_AscensionPrimalistDreamslip();
void AddSC_AscensionPrimalistDouse();
void AddSC_AscensionPrimalistNeptulonWrath();
void AddSC_AscensionConvenienceItems();
void AddSC_AscensionRaidDamageAuras();
void AddSC_AscensionBloodmageBloodShards();
void AddSC_AscensionPrimalistSacredGrove();
void AddSC_AscensionPrimalistAncientWar();
void AddSC_AscensionPrimalistEarthmotherRoar();
void AddSC_AscensionPrimalistRushHunt();
void AddSC_AscensionPrimalistCrushingEarth();
void AddSC_AscensionVenomancerCatalyst();
void AddSC_AscensionPrimalistSpiritBeast();
void AddSC_AscensionPrimalistWeapons();
void AddSC_AscensionPrimalistTalents();
void AddSC_AscensionPrimalistBones();
void AddSC_AscensionPrimalistBoons();
void AddSC_AscensionPrimalistSeismicResources();
void AddSC_AscensionPrimalistGuidance();
void AddSC_AscensionPrimalistBarrier();
void AddSC_AscensionPrimalistGrove();
void AddSC_AscensionPrimalistMountainFury();
void AddSC_AscensionPrimalistBoulder();
void AddSC_AscensionPrimalistUrsoc();
void AddSC_AscensionPrimalistTorn();
void AddSC_AscensionPrimalistRexxarMight();
void AddSC_AscensionPrimalistMineralization();
void AddSC_AscensionPrimalistLifeSpirit();
void AddSC_AscensionPrimalistTotem();
void AddSC_AscensionPrimalistHeavyHanded();
void AddSC_AscensionPrimalistTremor();
void AddSC_AscensionPrimalistPulverize();
void AddSC_AscensionPrimalistStoneTosser();
void AddSC_AscensionPrimalistVitality();
void AddSC_AscensionPrimalistMagmatism();
void AddSC_AscensionPrimalistGeomancy();
void AddSC_AscensionRunemasterTalents();
void AddSC_AscensionRunemasterTravel();
void AddSC_AscensionStormbringerLightning();
void AddSC_AscensionStormbringerTalents();
void AddSC_AscensionStormbringerThunderOrb();
void AddSC_AscensionStormbringerMysticThunder();
void AddSC_AscensionStormbringerWindGate();
void AddSC_AscensionStormbringerZephyr();
void AddSC_AscensionStormbringerDrown();
void AddSC_AscensionStormbringerPet();
void AddSC_AscensionStormbringerSphere();
void AddSC_AscensionStormbringerStormflow();
void AddSC_AscensionStormbringerFog();
void AddSC_AscensionStormbringerSurge();
void AddSC_AscensionStormbringerIonicAura();
void AddSC_AscensionBloodmageSecondary();
void AddSC_AscensionBloodmageHemostasis();
void AddSC_AscensionRangerSecondary();
void AddSC_AscensionRangerDirtyFighter();
void AddSC_AscensionRangerDeadeye();
void AddSC_AscensionRangerHookshot();
void AddSC_AscensionRangerOutmaneuver();
void AddSC_AscensionRangerToTheSkies();
void AddSC_AscensionRunemasterManuscription();
void AddSC_AscensionRangerTalents();
void AddSC_AscensionRangerFlowers();
void AddSC_AscensionRangerPetalkeeper();
void AddSC_AscensionRangerFalconstrike();
void AddSC_AscensionRangerArchery();
void AddSC_AscensionChronomancerTalents();
void AddSC_AscensionChronomancerTime();
void AddSC_AscensionChronomancerRenewal();
void AddSC_AscensionChronomancerMovement();
void AddSC_AscensionAdventurerCache();
void AddSC_AscensionBankVoucher();
void AddSC_AscensionRunePouches();
void AddSC_AscensionUpgradeKits();
void AddSC_AscensionProfessionRanks();
void AddSC_AscensionPrestigiousCache();
void AddSC_AscensionCallboardCache();
void AddSC_AscensionFeatherOfAncients();
void AddSC_AscensionVultureCultQuests();
void AddSC_AscensionCaravanCarts();
void AddSC_AscensionNorthshireRuins();
void AddSC_AscensionInnRest();
void AddSC_AscensionReaperRuin();
void AddSC_AscensionReaperRedshade();
void AddSC_AscensionReaperSpellContracts();
void AddSC_AscensionReaperTalentProcs();
void AddSC_AscensionPersonalBank();
void AddSC_AscensionWisdomball();
void AddSC_AscensionBloodmageTalents();
void AddSC_AscensionBloodmageVitality();
void AddSC_AscensionBloodmageProcs();
void AddSC_AscensionReaperReflexes();
void AddSC_AscensionPrimalistMountain();
void AddSC_AscensionChronomancerRipple();
void AddSC_AscensionChronomancerSecondary();
void AddSC_AscensionVenomancerSerpentFang();
void AddSC_AscensionVenomancerWasp();
void AddSC_AscensionSunClericBattleCleric();
void AddSC_AscensionReaperTalents();
void AddSC_AscensionReaperSecondary();
void AddSC_AscensionReaperReliquary();
void AddSC_AscensionReaperGhostClaw();
void AddSC_AscensionReaperAnimaAmbusher();
void AddSC_AscensionReaperMindScreech();
void AddSC_AscensionReaperBloodBinding();
void AddSC_AscensionReaperTormentedSouls();
void AddSC_AscensionPrimalistSecondary();
void AddSC_AscensionRunemasterSecondary();
void AddSC_AscensionRunemasterBurnedEtching();
void AddSC_AscensionRunemasterHurricane();
void AddSC_AscensionRunemasterRiftClones();
void AddSC_AscensionRunemasterDisappearance();
void AddSC_AscensionRunemasterTalentEffects();
void AddSC_AscensionRunemasterRunicTalents();
void AddSC_AscensionRunemasterElementalTalents();
void AddSC_AscensionRunemasterTalentProcs();
void AddSC_AscensionRunemasterTalentMechanics();
void AddSC_AscensionWelcomeWarchest();
void AddSC_AscensionClassBundleStore();
void AddSC_AscensionLfgObjective();
void AddSC_AscensionBushcraft();

void AddCoAScripts()
{
    AddAscensionStockCoefficientScripts();
    AddAscensionScalingBaseScripts();
    AddAscensionManastormScripts();
    AddSC_AscensionReaperDirge();
    AddAscensionTinkerOverloadScripts();
    AddAscensionCompatScripts();
    AddAscensionTravelPermitScripts();
    AddAscensionBarbarianCompletionScripts();
    AddAscensionBarbarianEventScripts();
    AddAscensionBarbarianAbilityScripts();
    AddAscensionGuardianStandardScripts();
    AddAscensionGuardianFavorScripts();
    AddAscensionGuardianEventScripts();
    AddAscensionGuardianCompletionScripts();
    AddAscensionGuardianAbilityScripts();
    AddAscensionGuardianTalentScripts();
    AddAscensionGuardianDrumScripts();
    AddAscensionRangerDamageScripts();
    AddAscensionRangerScalingScripts();
    AddAscensionRangerAssaultScripts();
    AddAscensionWitchHunterTonicScripts();
    AddAscensionWitchHunterTonicTalentScripts();
    AddAscensionWitchHunterTorchScripts();
    AddAscensionWitchHunterFlameScripts();
    AddAscensionWitchHunterTorchlightScripts();
    AddAscensionWitchHunterStakeScripts();
    AddAscensionWitchHunterCompletionScripts();
    AddAscensionWitchHunterEventScripts();
    AddAscensionWitchHunterAbilityScripts();
    AddAscensionWitchHunterDefenseScripts();
    AddAscensionWitchHunterSummonScripts();
    AddAscensionWitchDoctorCompletionScripts();
    AddAscensionWitchDoctorEventScripts();
    AddAscensionWitchDoctorAbilityScripts();
    AddAscensionWitchDoctorBrewingScripts();
    AddAscensionWitchDoctorAuraScripts();
    AddAscensionWitchDoctorSummonScripts();
    AddAscensionNecromancerScripts();
    AddAscensionNecromancerContractScripts();
    AddAscensionNecromancerSummonScripts();
    AddAscensionNecromancerEventScripts();
    AddAscensionNecromancerAbilityScripts();
    AddAscensionNecromancerAuraScripts();
    AddSC_AscensionXoroth();
    AddSC_AscensionStarcaller();
    AddSC_AscensionStarcallerContracts();
    AddSC_AscensionPyromancer();
    AddSC_AscensionPyromancerContracts();
    AddSC_AscensionPyromancerEvents();
    AddSC_AscensionPyromancerAbilities();
    AddSC_AscensionPyromancerAuras();
    AddSC_AscensionPyromancerSummons();
    AddSC_AscensionCultist();
    AddSC_AscensionCultistContracts();
    AddSC_AscensionCultistEvents();
    AddSC_AscensionCultistAbilities();
    AddSC_AscensionCultistAuras();
    AddSC_AscensionCultistSummons();
    AddSC_AscensionVenomancer();
    AddSC_AscensionVenomancerContracts();
    AddSC_AscensionVenomancerEvents();
    AddSC_AscensionVenomancerAbilities();
    AddSC_AscensionVenomancerAuras();
    AddSC_AscensionVenomancerSummons();
    AddSC_AscensionTinker();
    AddSC_AscensionTinkerContracts();
    AddSC_AscensionTinkerEvents();
    AddSC_AscensionTinkerAbilities();
    AddSC_AscensionTinkerAuras();
    AddSC_AscensionTinkerSummons();
    AddSC_AscensionSunCleric();
    AddSC_AscensionSunClericContracts();
    AddSC_AscensionSunClericEvents();
    AddSC_AscensionSunClericAbilities();
    AddSC_AscensionSunClericAuras();
    AddSC_AscensionSunClericSummons();
    AddSC_AscensionSunClericValkyrie();
    AddSC_AscensionSunClericDevotion();
    AddSC_AscensionSunClericRadiance();
    AddSC_AscensionStarcallerEvents();
    AddSC_AscensionStarcallerAbilities();
    AddSC_AscensionStarcallerAuras();
    AddSC_AscensionStarcallerMechanics();
    AddSC_AscensionXorothContracts();
    AddSC_AscensionXorothEvents();
    AddSC_AscensionXorothAbilities();
    AddSC_AscensionXorothAuras();
    AddSC_AscensionXorothSummons();
    AddSC_AscensionFelsworn();
    AddSC_AscensionFelswornContracts();
    AddSC_AscensionFelswornAuras();
    AddSC_AscensionFelswornEvents();
    AddSC_AscensionFelswornAbilities();
    AddSC_AscensionFelswornSummons();
    AddSC_AscensionTemplar();
    AddSC_AscensionTemplarContracts();
    AddSC_AscensionTemplarAuras();
    AddSC_AscensionTemplarEvents();
    AddSC_AscensionTemplarAbilities();
    AddSC_AscensionTemplarSummons();
    AddSC_AscensionTemplarTemporaryLibramProcs();
    AddSC_AscensionTemplarTithe();
    AddAscensionTinkerAugmentationScripts();
    AddAscensionTinkerAugmentationTalentScripts();
    AddAscensionTinkerHackingScripts();
    AddSC_AscensionPrimalistEarthshaping();
    AddSC_AscensionPrimalistHeavyEarth();
    AddSC_AscensionPrimalistEarthshaker();
    AddSC_AscensionPrimalistRunningInstinct();
    AddSC_AscensionPrimalistRideWave();
    AddSC_AscensionPrimalistPowerHammer();
    AddSC_AscensionPrimalistEmeraldWill();
    AddSC_AscensionPrimalistTotemicEchoes();
    AddSC_AscensionPrimalistWildCarnage();
    AddSC_AscensionPrimalistPendant();
    AddSC_AscensionPrimalistThorns();
    AddSC_AscensionPrimalistBloodyClaws();
    AddSC_AscensionPrimalistJudgement();
    AddSC_AscensionPrimalistShattering();
    AddSC_AscensionPrimalistPrecision();
    AddSC_AscensionPrimalistVerdantChase();
    AddSC_AscensionPrimalistJourney();
    AddSC_AscensionPrimalistQuakingThane();
    AddSC_AscensionPrimalistTremors();
    AddSC_AscensionPrimalistCataclysm();
    AddSC_AscensionPrimalistFaePresence();
    AddSC_AscensionPrimalistEarthsGuidance();
    AddSC_AscensionPrimalistGroveTender();
    AddSC_AscensionPrimalistBramblepatch();
    AddSC_AscensionPrimalistPrimalStrikes();
    AddSC_AscensionPrimalistLithicLance();
    AddSC_AscensionPrimalistEmpoweredBoons();
    AddSC_AscensionPrimalistEarthmotherWarden();
    AddSC_AscensionPrimalistDruidTraining();
    AddSC_AscensionPrimalistSpiritualFrenzy();
    AddSC_AscensionPrimalistPhysicalCrit();
    AddSC_AscensionPrimalistRipsAndTears();
    AddSC_AscensionPrimalistMountainAvatar();
    AddSC_AscensionPrimalistRylaksBite();
    AddSC_AscensionPrimalistRylaksBlessing();
    AddSC_AscensionPrimalistWildheart();
    AddSC_AscensionPrimalistDreamslip();
    AddSC_AscensionPrimalistDouse();
    AddSC_AscensionPrimalistNeptulonWrath();
    AddSC_AscensionConvenienceItems();
    AddSC_AscensionRaidDamageAuras();
    AddSC_AscensionBloodmageBloodShards();
    AddSC_AscensionPrimalistSacredGrove();
    AddSC_AscensionPrimalistAncientWar();
    AddSC_AscensionPrimalistEarthmotherRoar();
    AddSC_AscensionPrimalistRushHunt();
    AddSC_AscensionPrimalistCrushingEarth();
    AddAscensionRunemasterGlyphScripts();
    AddSC_AscensionVenomancerCatalyst();
    AddAscensionRunemasterBrandScripts();
    AddAscensionRunemasterScalingScripts();
    AddAscensionTinkerRockadierScripts();
    AddSC_AscensionPrimalistSpiritBeast();
    AddSC_AscensionPrimalistWeapons();
    AddSC_AscensionPrimalistTalents();
    AddSC_AscensionPrimalistBones();
    AddSC_AscensionPrimalistBoons();
    AddSC_AscensionPrimalistSeismicResources();
    AddSC_AscensionPrimalistGuidance();
    AddSC_AscensionPrimalistBarrier();
    AddSC_AscensionPrimalistGrove();
    AddSC_AscensionPrimalistMountainFury();
    AddSC_AscensionPrimalistBoulder();
    AddSC_AscensionPrimalistUrsoc();
    AddSC_AscensionPrimalistTorn();
    AddSC_AscensionPrimalistRexxarMight();
    AddSC_AscensionPrimalistMineralization();
    AddSC_AscensionPrimalistLifeSpirit();
    AddSC_AscensionPrimalistTotem();
    AddSC_AscensionPrimalistHeavyHanded();
    AddSC_AscensionPrimalistTremor();
    AddSC_AscensionPrimalistPulverize();
    AddSC_AscensionPrimalistStoneTosser();
    AddSC_AscensionPrimalistVitality();
    AddSC_AscensionPrimalistMagmatism();
    AddSC_AscensionPrimalistGeomancy();
    AddSC_AscensionRunemasterTalents();
    AddSC_AscensionRunemasterTravel();
    AddSC_AscensionStormbringerLightning();
    AddSC_AscensionStormbringerTalents();
    AddSC_AscensionStormbringerThunderOrb();
    AddSC_AscensionStormbringerMysticThunder();
    AddSC_AscensionStormbringerWindGate();
    AddSC_AscensionStormbringerZephyr();
    AddSC_AscensionStormbringerDrown();
    AddSC_AscensionStormbringerPet();
    AddSC_AscensionStormbringerSphere();
    AddSC_AscensionStormbringerStormflow();
    AddSC_AscensionStormbringerFog();
    AddSC_AscensionStormbringerSurge();
    AddSC_AscensionStormbringerIonicAura();
    AddSC_AscensionBloodmageSecondary();
    AddSC_AscensionBloodmageHemostasis();
    AddSC_AscensionRangerSecondary();
    AddSC_AscensionRangerDirtyFighter();
    AddSC_AscensionRangerDeadeye();
    AddSC_AscensionRangerHookshot();
    AddSC_AscensionRangerOutmaneuver();
    AddSC_AscensionRangerToTheSkies();
    AddSC_AscensionRunemasterManuscription();
    AddSC_AscensionRangerTalents();
    AddSC_AscensionRangerFlowers();
    AddSC_AscensionRangerPetalkeeper();
    AddSC_AscensionRangerFalconstrike();
    AddSC_AscensionRangerArchery();
    AddSC_AscensionChronomancerTalents();
    AddSC_AscensionChronomancerTime();
    AddSC_AscensionChronomancerRenewal();
    AddSC_AscensionChronomancerMovement();
    AddSC_AscensionAdventurerCache();
    AddSC_AscensionBankVoucher();
    AddSC_AscensionRunePouches();
    AddSC_AscensionUpgradeKits();
    AddSC_AscensionProfessionRanks();
    AddSC_AscensionPrestigiousCache();
    AddSC_AscensionCallboardCache();
    AddSC_AscensionFeatherOfAncients();
    AddSC_AscensionVultureCultQuests();
    AddSC_AscensionCaravanCarts();
    AddSC_AscensionNorthshireRuins();
    AddSC_AscensionInnRest();
    AddSC_AscensionReaperRuin();
    AddSC_AscensionReaperRedshade();
    AddSC_AscensionReaperSpellContracts();
    AddSC_AscensionReaperTalentProcs();
    AddSC_AscensionPersonalBank();
    AddSC_AscensionWisdomball();
    AddSC_AscensionBloodmageTalents();
    AddSC_AscensionBloodmageVitality();
    AddSC_AscensionBloodmageProcs();
    AddSC_AscensionReaperReflexes();
    AddSC_AscensionPrimalistMountain();
    AddSC_AscensionChronomancerRipple();
    AddSC_AscensionChronomancerSecondary();
    AddSC_AscensionVenomancerSerpentFang();
    AddSC_AscensionVenomancerWasp();
    AddSC_AscensionSunClericBattleCleric();
    AddSC_AscensionReaperTalents();
    AddSC_AscensionReaperSecondary();
    AddSC_AscensionReaperReliquary();
    AddSC_AscensionReaperGhostClaw();
    AddSC_AscensionReaperAnimaAmbusher();
    AddSC_AscensionReaperMindScreech();
    AddSC_AscensionReaperBloodBinding();
    AddSC_AscensionReaperTormentedSouls();
    AddSC_AscensionPrimalistSecondary();
    AddSC_AscensionRunemasterSecondary();
    AddSC_AscensionRunemasterBurnedEtching();
    AddSC_AscensionRunemasterHurricane();
    AddSC_AscensionRunemasterRiftClones();
    AddSC_AscensionRunemasterDisappearance();
    AddSC_AscensionRunemasterTalentEffects();
    AddSC_AscensionRunemasterRunicTalents();
    AddSC_AscensionRunemasterElementalTalents();
    AddSC_AscensionRunemasterTalentProcs();
    AddSC_AscensionRunemasterTalentMechanics();
    AddAscensionRunemasterZenithScripts();
    AddAscensionRunemasterEchoesScripts();
    AddAscensionVenomancerVenomScripts();
    AddAscensionVenomancerVenomProcScripts();
    AddAscensionVenomancerVenomTalentScripts();
    AddAscensionVenomancerVenomPayloadScripts();
    AddAscensionTinkerCombatSymbiosisScripts();
    AddCoABugReportScripts();
    AddCoAPlayerTicketScripts();
    AddAscensionAccountInfoScripts();
    AddCoAGameplayTestScripts();
    AddSC_AscensionResourceTalents();
    AddSC_AscensionRulesets();
    AddSC_AscensionMercenary();
    AddSC_AscensionHighRisk();
    AddSC_AscensionBloodforged();
    AddSC_AscensionPvpPower();
    AddSC_AscensionRestingBuff();
    AddSC_AscensionClosestResurrection();
    AddSC_AscensionThreatRedirect();
    AddSC_AscensionKeepersScrollSteadfast();
    AddSC_AscensionProfessionSpellAffect();
    AddSC_AscensionKeepersScrollZoneBuff();
    AddSC_AscensionWelcomeWarchest();
    AddSC_AscensionClassBundleStore();
    AddSC_AscensionLfgObjective();
    AddSC_AscensionBushcraft();
}
