-- Generated by worldforged-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- The Worldforged upgrade recipes, rebuilt from the client's own data: the
-- family of an upgrade is stored in ItemAddon.dbc, where column f40 of the
-- upgraded variant points at its base item. 1738 first-rank upgrades survive
-- that way, 651 weapons and 1087 pieces of armour, and every base and target
-- row already exists in item_template.
--
-- The cost is NOT recovered. No captured store response survives and no
-- ItemExtendedCost row names a Worldforged base item. The numbers are computed
-- from Blizzard's own slot weights, so the progression follows a known logic
-- rather than an invented one. Replace the column and nothing else changes.

DROP TABLE IF EXISTS `worldforged_upgrade`;
CREATE TABLE `worldforged_upgrade` (
  `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store`       TINYINT UNSIGNED NOT NULL COMMENT '8 武器，9 护甲 - 客户端自有的 Enum.CustomStores',
  `base_item`   INT UNSIGNED NOT NULL COMMENT '购买时消耗',
  `target_item` INT UNSIGNED NOT NULL COMMENT '发放',
  `cost`        INT UNSIGNED NOT NULL COMMENT '飞升符文，物品 375250；已计算，未恢复',
  PRIMARY KEY (`id`),
  UNIQUE KEY `base` (`base_item`),
  KEY `store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
