-- Generated by worldforged-werkzeug/sql_bauen.py. Do not edit by hand.
--
-- The Worldforged upgrade recipes, rebuilt from the client's own data: the
-- family of an upgrade is stored in ItemAddon.dbc, where column f40 of the
-- upgraded variant points at its base item. 1738 first-rank upgrades survive
-- that way, 651 weapons and 1087 pieces of armour, and every base and target
-- row already exists in item_template.
--
-- The cost is NOT recovered. No captured store response survives and no
-- ItemExtendedCost row names a Worldforged base item. The numbers are computed
-- from Blizzard's own slot weights, so the progression follows a known logic
-- rather than an invented one. Replace the column and nothing else changes.

-- Entry, name and subtitle come from creaturecache.wdb and Creature.dbc. The
-- same record was seen on the Area 52, Bronzebeard, Darkmoon and Vol'jin
-- caches. Where he stood is not recovered; see 04_worldforged_spawns.sql for
-- what the spawns there are based on instead.
DELETE FROM `creature_template` WHERE `entry` = 9780012;
INSERT INTO `creature_template`
 (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`npcflag`,`unit_class`,
  `rank`,`speed_walk`,`speed_run`,`type`,`type_flags`,`RegenHealth`,
  `flags_extra`,`AIName`,`ScriptName`)
VALUES
 (9780012,'时间守护者','飞升符文',80,80,35,1,1,
  0,1,1.14286,7,0,1,
  2,'','npc_worldforged_guardian');

DELETE FROM `creature_template_model` WHERE `CreatureID` = 9780012;
INSERT INTO `creature_template_model`
 (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`)
VALUES (9780012,0,48516,1,1);

-- The live realms report display 254545 for this entry, but that id
-- exists in no CreatureDisplayInfo.dbc - not in the server set and not in the
-- client, checked as far as patch-M, which owns the table. Their server sent a
-- display this client cannot resolve, so it is unusable here. The core skips
-- any creature_model_info row whose display the DBC does not know, Creature
-- Create then fails, and `.npc add` answers with its own usage text.
--
-- 48516 is attested for the same entry in three other caches, there under
-- the name Nozdormu, and resolves to Creature/Nozdormu/Nozdormu.mdx. It exists
-- in the DBC and suits a guardian of time. The numbers below are the collision
-- box, taken from the Nozdormu that already stands in this world.
DELETE FROM `creature_model_info` WHERE `DisplayID` = 48516;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`)
VALUES (48516,3.5,35,2);

DELETE FROM `npc_text` WHERE `ID` = 9780012;
INSERT INTO `npc_text` (`ID`,`text0_0`,`text0_1`,`VerifiedBuild`)
VALUES (9780012,'时间会磨灭一切。把世界锻造之物带给我，再带来足够的符文，我将让它重归完整。','时间会磨灭一切。把世界锻造之物带给我，再带来足够的符文，我将让它重归完整。',1);
